version: "3"

services:
  base:
    container_name: ddev_docs
    environment:
      - FRESHDESKAPITOKEN
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start