site_name: DDEV-Live

google_analytics:
  - 'UA-105593079-5'
  - 'auto'

theme:
  name: 'material'
  palette:
    primary: 'light-blue'

nav:
    - Home: index.md
    - User Guide:
        - Getting started with Drupal: getting-started.md
        - Getting started with TYPO3: typo3-getting-started.md
        - Help & Support: support.md
        - FAQs: faq.md
    - Tutorials:
        - CI/CD with Jenkins: cicd-integration.md
    - About:
        - Welcome to DDEV-Live: welcome.md
        - Release Notes: MISSING.md
        - Roadmap: roadmap.md
        - Known issues: known-issues.md
        - Contributing: https://github.com/drud/community/blob/master/governance.md
        - License: https://github.com/drud/docs/blob/master/LICENSE.MD

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en

extra_javascript:
  - 'js/extra.js'