site_name: DDEV-Live

google_analytics:
  - 'UA-105593079-5'
  - 'auto'

theme:
  name: 'material'
  palette:
    primary: 'light-blue'

nav:
    - Home: index.md
    - Introduction and Philosophy: introduction.md
    - Auth and Orgs:
        - Accounts: account-types.md
        - Authentication: authentication.md
        - Administration: administration.md
        - Organizations: organizations.md
    - Working with Providers:
        - Overview: providers.md
        - Github: github.md
    - Working with Sites:
        - Overview: placeholder.md
        - site: placeholder.md
        - filestore: placeholder.md
        - database: placeholder.md
        - jobs: placeholder.md
        - status: placeholder.md
        - hostnames: hostnames.md
        - tls: placeholder.md
        - variables: placeholder.md
        - guides:
            - Drupal: getting-started.md
            - TYPO3: typo3-getting-started.md
            - WordPress: placeholder.md
    - Working with Assets:
        - databases: placeholder.md
        - files: placeholder.md
    - CI/CD:
        - Overview: placeholder.md
        - jenkins: cicd-integration.md
        - CircleCI: placeholder.md
    - Finding Help:
        - FAQs: faq.md
        - support: support.md
        - slack: placeholder.md
        - discourse: placeholder.md
    - About:
        - Roadmap: roadmap.md
        - Known issues: known-issues.md
        - Contributing: https://github.com/drud/community/blob/master/governance.md
        - License: https://github.com/drud/docs/blob/master/LICENSE.md

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en

extra_javascript:
  - 'js/extra.js'