site_name: DDEV-Live

google_analytics:
  - 'UA-105593079-5'
  - 'auto'

theme:
  name: 'material'
  palette:
    primary: 'light-blue'

nav:
    - Home: index.md
    - Introduction and Philosophy: introduction.md
    - Getting Started: getting-started.md
    - Auth and Orgs:
        - accounts: account-types.md
        - authentication: authentication.md
        - administration: administration.md
        - organizations: organizations.md
    - Providers:
        - provider: providers.md
        - gitHub: github.md
    - Working with Sites:
        - backups: backups.md
        - databases: databases.md
        - execs: exec.md
        - files: files.md
        - guides:
            - Drupal: drupal-guide.md
            - TYPO3: typo3-guide.md
            - WordPress: placeholder.md
        - restores: placeholder.md
        - sites: sites.md 
        - jobs: placeholder.md
        - hostnames: hostnames.md
        - tls: tls.md
        - variables: placeholder.md
    - CI/CD:
        - Jenkins: jenkins.md
        - CircleCI: placeholder.md
    - Finding Help:
        - community: placeholder.md
        - support: support.md
        - FAQs: faq.md
    - About:
        - Roadmap: roadmap.md
        - Known issues: known-issues.md
        - Contributing ⧉: https://github.com/drud/community/blob/master/governance.md
        - License ⧉: https://github.com/drud/docs/blob/master/LICENSE.md

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en

extra_javascript:
  - 'js/extra.js'
